name: Checkout submodule
description: Checkout submodule
author: Mushus
inputs:
  basePath:
    description: A path to execute git operation
    required: false
    default: .
  submodulePath:
    description: A path of submodule directory
    required: true
  identifierFile:
    description: A identifier secret key to used checkout the submodule
    required: false
runs:
  using: "node12"
  main: "dist/install/index.js"
  post: "dist/uninstall/index.js"
  post-if: always()
branding:
  icon: 'archive'
  color: 'gray-dark'
